services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    user: "1000:1000"
    restart: unless-stopped
    environment:
      ADMIN_TOKEN: ${ADMIN_TOKEN}
      TZ: Europe/Madrid
    volumes:
      - ./data:/data

# añadir estas líneas al final del archivo para proxy inverso 
networks:
  default:
    external: true
    name: proxy